# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2943ccc5ed07f360cc0c4c9484729dec293b219f3edba052f82880fb5c98ba4e8eec2759eb9ed72a5f489e92c1360e38372b32fb98bf54ccf9638ceab21586c7

test:
  secret_key_base: 4aaeeca0c0f5500c9419583422b0de0499f7067439cbfeb1824f7dc2aa1936121a66d2bbd94b4f3c1652f3f7a70a86c2321bdcb309e3b2fa61bb0d1e6d0c5933

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
